### PR TITLE
Update Core Set cards

### PR DESCRIPTION
**Pull request by rushl**
Add backs to Investigator cards, add class to mini cards, add defined back to Predator or Prey Agenda card.

### CODE REVIEW

**Comment by GeckoTH** [comment]
Predator or Prey shouldn't have a defined back, since we're using a "hack" to swap between that card and the Masked Hunter card. OCTGN doesn't currently allow you to have different "cardsize" for alternates of a card, so we can't have Agenda on the front and Enemy on the back, since they're different "sizes" (horizontal vs vertical card).

**Comment by rushl** [comment]
Hmm, I can say that it seems to work fine. Using that set, if you flip the Agenda card, it properly orients the monster and he looks great. For a horrible creature, that is.

**Comment by GeckoTH** [comment]
Did you remove my hack in the flip card function that replaces Predator or Prey with Masked Hunter when flipping it?

**Comment by rushl** [comment]
So, I've modified the macro in the excel sheet so that it applies the 'size' property to the 'alternate' tags. It does appear that OCTGN will respect the proper size instruction on 'alternate' cards as if they were 'card' tags. So, I've removed the workaround patch, and flipping from the agenda to the hunter works as expected!

**Comment by hone** [comment]
@GeckoTH I can confirm this works. I tested it locally and the flipping works fine. We'll need to update the image pack to only use one octgn UUID.

**Comment by hone** [comment]
nevermind, `947bb975-8eb2-45a7-bc68-ea58a50190da` is needed for the 03 decklist. We're good to go.

**Pull request merged**
