### PR TITLE
Add missing Sets to Card Database

### PR DESCRIPTION
**Pull request by ChristopherS**
I noticed that AHLCG-DB.xlsm hasn't been updated for the last 8 months, so I added the new sets. 
I also payed attention to using the same GUIDs from the set.xml files that are already there.

### CODE REVIEW

**Comment by KenDdoox** [comment]
Could you explain what that file does? I'm assuming it's to keep track of the database, because it doesn't affect the game. Together with 2 other people, I'm maintaining updates on the repo with pack releases, and I don't find this file of any use, tbh.

Side question, do you use a code to update this file and to sync it with the existing GUIDs? I actually had a thought of updating this by hand when I first started making the set.xml files, but that's just too much work, and also as said before, I don't really know if this file actually do anything so I just ignored it :P

**Comment by ChristopherS** [comment]
As far as I can tell, the database is (or rather was, as it seems) used to export the set.xml files. With the Set_Editor file you can import all cards from a set from arkhamdb, then you just need add the GUIDs, copy the cards over to the Database file and export it as a set.xml. I don't know how create these files, but it took me less than 5 minutes per set to create the xml with this.

I got the idea to update this file, after downloading the repo and trying to build it with o8build. While doing this I got the following error message:
`line: 2 position: 147 msg: Das standalone-Attribut wurde nicht deklariert. file: D:\arkham_octgn\o8g\Sets\Before the Black Throne\set.xml`
(Can be translated as "The sandalone-attribute  was not declared")
Trying to find out where the problem is, I noticed that there were inconsitencies between the xml files from the sets included in the Database
`<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<set xmlns:noNamespaceSchemaLocation="CardSet.xsd" name="A Phantom of Truth" id="d740b66f-3983-45e4-9b6c-0dcc35f6ed13" gameId="a6d114c7-2e2a-4896-ad8c-0330605c90bf" gameVersion="1.0.0.0" version="1.0.0">`
and the sets added later
`<?xml version='1.0' encoding='UTF-8'?>
<set gameId="a6d114c7-2e2a-4896-ad8c-0330605c90bf" gameVersion="1.0.0.0" id="95daca66-e3e6-4e72-a1c5-1765aea578a0" name="Before the Black Throne" standalone="True" version="1.0.0" xmlns:noNamespaceSchemaLocation="CardSet.xsd">`

That basically got me into finding out how the Database works, so I can get the game to build for me.

As for the code I used for the GUIDs, I quickly wrote a small Python-Script to get me all GUIDs in the xml and print them into a text file.
`fi = open("set.xml", "r")
fo = open("IDs.txt", "w")

xml = fi.read()

fi.close()

while True:
    loc = xml.find("id=")
    if(loc == -1):
        break
    guid = xml[loc+4:loc+40]
    xml = xml[loc+40:]
    fo.write(guid + "\n")    

fo.close()`

I hope that helps.

**Comment by KenDdoox** [comment]
When I began making the set.xml files for packs, I was trying to get it from ArkhamDB, but that didn't do too well, as the site is updated quite late (later than CardgameDB). Then I was introduced to a script that scrapes data from CardgameDB and stuck with it from then on. That probably explains why there was a difference in the set.xml files from earlier versions.

If you're on Discord, we can talk more about this and updating the repo more easily :D

**Comment by ChristopherS** [comment]
I am on Discord. Christopher#9952

**Pull request merged**
