### PR TITLE
Add ability to spawn any card needed.

### PR DESCRIPTION
**Pull request by rushl**

### CODE REVIEW

**Comment by hone** [comment]
I wonder if people will be confused here that this actually creates a new instance of the card vs. finding an existing version if it's already loaded in the deck.

**Comment by rushl** [comment]
Perhaps that could be alleviated with the proper wording in the menu? Right now it's just "Add Card". We could make it "Create New Card" or something similar.

**Comment by hone** [comment]
The idea is good, but without familiarity with how OCTGN works people 
might miss the subtly here.

**Comment by wlk0** [comment]
"Draw from collection" ?

**Comment by rushl** [comment]
I feel like it is pretty clear what's going on. It pops up a window with every card in the set - all player cards, encounter cards, acts, agendas, etc. Not only that, but every card in every set loaded. So if you've got Rougarou installed, those cards are present too. So it will be unlikely that a user will believe they are looking for cards in the local decks. (Note you do have a nice filter, to narrow down what you're looking for.)

The best reason to include this feature would be to give some ability for the player to be flexible with future scenario decks. Right now, I believe that all the scenario decks include every card you'd need. But that might not always be the case. Or a player might realize they meant to use card X or Y, or decide to change something last minute for whatever reason. As it is now, there is no way to save a game, and fix the issue. You either have to play on without whatever card you wish you had, or cancel everything and start over. I think either of those options are bad. 

I believe that the feature could be very useful. I do agree that it needs to be named better.  "Add Card" isn't very clear, and could be confusing. It comes down to finding the best wording. I might suggest:

1) Spawn Card From Set
2) Generate New Card
3) Fetch Card From Box

And the two previous suggestions:
4) Draw from collection (wlk0)
5) Create New Card

Of course, we're not limited to those, if there's something that is more clear I've not thought of. Or if shuffling a few of the verbs and nouns above helps. :)

**Comment by GeckoTH** [comment]
I think this idea is worth exploring, and could prove useful. Though keep in mind that you can actually bring a card in currently if you wish, albeit requires a couple of steps. A player can alt-tab out of the game window, open up the Deck Editor, add whatever card(s) he needs to his player setup pile or wherever. Then save and load that "deck" in game. Not elegant, but at least the option is there until this idea gets worked out.

**Comment by rushl** [comment]
Wouldn't re-loading the player deck trigger a re-draw of the hand, as the process of loading player decks automatically draws the first hand?

**Comment by rushl** [comment]
A different approach to this has just occurred to me. Instead of presenting it as a menu option, could it just be added as a hot-key option? That way it wouldn't be visible to the average user, but it could noted and explained in detail wherever the eventual host of the module would be. Then, more advanced users could just hit the hot-key. Sort of like a "hidden" feature.

**Comment by rushl** [comment]
Closing this PR as it is out of date, and I've updated the menu command. See PR #69 .

**Pull request closed without merging**
